version: '3.4'

services:
  api:
    image: ${DOCKER_IMAGE:-it.bz.noi.calendar-api}:${DOCKER_TAG:-latest}
    build:
      context: ../
      dockerfile: infrastructure/docker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      CLIENT_ID: ${CLIENT_ID}
      TENANT_ID: ${TENANT_ID}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      MEETING_ROOMS: ${MEETING_ROOMS}
      NUMBER_OF_EVENTS: ${NUMBER_OF_EVENTS}      
      OPENID_AUTHORITY: ${OPENID_AUTHORITY}
    ports:
      - "60209:80"
