version: '3.4'

services:
  api:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      CLIENT_ID: ${CLIENT_ID}
      TENANT_ID: ${TENANT_ID}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      MEETING_ROOMS: ${MEETING_ROOMS}
      NUMBER_OF_EVENTS: ${NUMBER_OF_EVENTS}      
      OPENID_AUTHORITY: ${OPENID_AUTHORITY}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:80"
